### ISSUE TITLE
Move to `visimp.teapot.ovh`

### ISSUE THREAD

**Issue by foxyseta** [visimp/pages#1]
Move this website to `visimp.teapot.ovh`. Remember to update:
- [x] `hugo.toml`
- [x] `github/workflows/`
- [x] link on the repository's main page
- [x] link on the organization's profile

**Comment by lucat1** [comment]
I think the quickest and simplest (not to mention, most reliable) option is to just use GitHub pages as the actual http server and just point `visimp.teapot.ovh` to GitHub pages. If it's ok for you can do this.

**Comment by foxyseta** [comment]
Yes, that's perfect

**Comment by lucat1** [comment]
The DNS setup is done and the website is now available at [visimp.teapot.ovh](https://visimp.teapot.ovh).
That said, it appears to be broken. I suppose the URL for the resources is hardcoded somewhere to the old URL.

**Comment by lucat1** [comment]
Alright, 097b836 should fix it.
